### ISSUE TITLE
Ревью 1-го задания

### ISSUE THREAD

**Issue by sergey-shambir** [bogdanov-d-a/JsSynchronizationCourse#1]
* предлагаю выделить скрипт из `html`-файла в отдельный `js`-файл в подкаталоге `js`
* метод `getPromiseOne` предлагаю переименовать в `loadOneImage`, т.к. основная цель метода не возвращать Promise, а загружать изображение
* метод `asyncMapParallel` считаю наиболее удачной реализацией, но я бы предложил в нём применить Promise.all - это сильно упростит код, фактически всё свернётся в одну строку, которую можно будет заинлайнить в asyncParallel
* метод asyncParallel предлагаю переменовать в `loadImages`

**Comment by sergey-shambir** [comment]
Предлагаю также поместить решения для 1-го и 2-го задания в разные каталоги. Будет некоторое дублирование, но зато гораздо легче просматривать.

**Comment by bogdanov-d-a** [comment]
3. Если так сделать, тогда реализация asyncParallel будет полностью повторять реализацию loadImages. Пусть велосипед для Promise.all останется.
* Решение 1 задания выделено в бранч task1.

**Comment by sergey-shambir** [comment]
Тогда ОК
